services:
  telegram_bot:
    build:
      context: ./telegram_bot
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: telegram_bot/.env

  redis:
    image: redis:7.4.2
    restart: unless-stopped
    env_file: redis/.env
    expose: 
      - "6379"
    volumes:
      - redis_volume:/data

  postgres:
    image: postgres:17.4
    restart: unless-stopped
    env_file: postgres/.env
    expose: 
      - "5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

volumes:
  redis_volume:

  postgres_volume:
